#!/system/bin/sh

# HACK: patch simple2ext's script to prevent filesystem corruption
S2ECONFIG="/data/local/s2e_config/.mounts_ext4"
if [ -f $S2ECONFIG ]; then
    rm $S2ECONFIG
fi

# HACK: migrate eth0 -> wlan0 in wpa_supplicant.conf
WPACONFIG="/data/misc/wifi/wpa_supplicant.conf"
if [ $(cat $WPACONFIG | grep "ctrl_interface=eth0") ]; then
    sed -e 's/ctrl_interface=eth0/ctrl_interface=wlan0/g' -i $WPACONFIG
fi

# HACK: enable compcache
#compcache start

# HACK: enable swap
swapon /dev/block/mmcblk0p3
